package.json, src/components/ViewAgreement/Sections/AgreementLines.js
Just getting us onto the versions that are currently being released in prep for the Q3 release.
=> Upgrade Folio deps

src/components/Agreements/ViewAgreement/Sections/AgreementInfo.js, src/components/Agreements/ViewAgreement/Sections/VendorInfo.css, src/components/Agreements/ViewAgreement/ViewAgreement.js
- Added Expand/Collapse all button
- Removed duplicated Agreement status field
- Added comments to the CSS on VendorInfo
=> UIER-5: Tweaks to Agreement detail view

src/components/Agreements/AgreementForm/AgreementForm.js, src/components/Agreements/EditAgreement/EditAgreement.js, src/components/Agreements/ViewAgreement/Sections/VendorInfo.js, src/components/Agreements/ViewAgreement/ViewAgreement.js, src/routes/Agreements.js, translations/ui-erm/en.json
Implemented the fields required for UIER-17's create/edit agreement form.
Includes:
- Name (Required Textfield)
- Description (Textarea)
- Agreement Start Date (Required Datepicker)
- Agreement End Date (Datepicker)
- Agreement Cancellation Deadline (Datepicker)
- Agreement Status (Required Dropdown fed via refdata values)
- Renewal Priority (Dropdown fed via refdata values)
- Is Perpetual (Dropdown fed via refdata values)
=> UIER-17: Edit/Create Agreements

src/routes/Agreements.js, translations/ui-erm/en.json
Added new visible columns to the Agreements list view per UIER-4.
=> UIER-4: Agreements: Added columns to table

src/routes/Agreements.js, src/routes/EResources.js, src/util/getSASParams.js, translations/ui-erm/en.json
Added two filter groups for the E-resources page to filter by resource type and whether a resource is a package or not, [per mockup](https://drive.google.com/file/d/1BYhArmCYx7keyZ5MAUbnUto6wIIsu-21/view).
=> UIER-2 Eresources: Added filters for 'Type' and 'Is Package'

package.json
Missed a reference in the subpermission
=> Fixed subpermission ref

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/es.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/pt_BR.json
=> Update translation strings as of 20181128T202334

package.json, src/ERM.js, src/components/Tabs/Tabs.js, test/ui-testing/basket.js, test/ui-testing/nav.js
- Removed Dashboard button and route.
- Switched to using `ButtonGroup` component instead of deprecated `SegmentedControl`.
- Updated tests and fixed default run parameters to include `--show` argument
=> ButtonGroup and Tests

src/components/Agreements/AgreementForm/Sections/AgreementFormInfo.js, src/components/Agreements/ViewAgreement/Sections/AgreementInfo.js
Cleaned up some of the accordion logic.
=> Agreement Info: Simplified accordion logic

CHANGELOG.md, package.json, src/index.js, src/routes/Agreements.js
Need to export the Agreements SAS and pass into props to the SAS
=> Added support for plugin-find-agreement

CHANGELOG.md, src/components/Agreements/AgreementFilters/AgreementFilters.js, src/components/Agreements/AgreementFilters/index.js, src/components/OrganizationSelection/OrganizationSelectionContainer.js, src/routes/Agreements.js, src/util/getSASParams.js
- Switched to using the new `renderFilters` functionality in `SearchAndSort`.
- Ported existing Status, Renewal Priority, and Is Perpetual filters to `CheckboxFilter`.
- Added new Organizations filter.
=> Agreement Filters

CHANGELOG.md, package.json, src/components/Agreements/AgreementFilters/AgreementFilters.js
=> Release 2.0.0

Jenkinsfile, package.json, src/components/Basket/BasketList.js, test/ui-testing/agreement-crud.js, test/ui-testing/basket.js, test/ui-testing/nav.js
`role="listitem"` is no longer used so we need a different way of selecting MCL's data rows.
=> Fixed tests to deal with changes to MCL

src/components/Agreements/ViewAgreement/Sections/EresourceAgreementLines.js, src/components/EResources/ViewTitle/Sections/AcquisitionOptions.js
✅ Fixed bug where following links to resources could throw a 404 error
✅ Fixed bug where agreement entitlements for a package weren't being properly rendered
=> ERM-3 and ERM-4: Bug fixes

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/zh_CN.json
=> Update translation strings as of 20190306T161944

translations/ui-agreements/it_IT.json, translations/ui-agreements/pt_BR.json
=> Update translation strings as of 20190313T213403

src/components/EResources/ViewTitle/Sections/TitleInfo.js, src/components/ResourceType/ResourceType.js, src/routes/EResources.js, src/util/getResourceIdentifier.js, translations/ui-agreements/en.json
Show identifiers in EResources table and preview.
=> ERM-89 ERM-90: EResource Identifiers

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/zh_CN.json
=> Update translation strings as of 20190322T150534

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/zh_CN.json
=> Update translation strings as of 20190401T154238

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/zh_CN.json
=> Update translation strings as of 20190405T144349

src/components/Agreements/AgreementForm/Sections/AgreementFormLines.js, src/components/Agreements/AgreementForm/components/AgreementLinesFieldArray.css, src/components/Agreements/AgreementForm/components/AgreementLinesFieldArray.js, translations/ui-agreements/en.json
Agreement lines should have a selected resource before the user is allowed to put/post that agreement.
=> ERM-221: Added validator for empty agreement lines

src/components/Agreements/AgreementFilters/AgreementFilters.js, src/routes/Agreements.js
- Clearing organizations filter now also clears the organization role filter
- Removed separators between filters
=> ERM-212 ERM-238: Fixed clearing org filter

src/components/Agreements/AgreementForm/components/EditCard.css, src/components/Agreements/AgreementForm/components/EditCard.js
`EditCard` only needs to provide the trash icon and callback wiring now.
=> Use new Card component to compose EditCard

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/zh_CN.json
=> Update translation strings as of 20190528T121921

translations/ui-agreements/pt_BR.json
=> Update translation strings as of 20190611T141613

CHANGELOG.md, package.json, src/components/Agreements/AgreementForm/Sections/AgreementFormExternalLicenses.js, src/components/Agreements/AgreementForm/Sections/AgreementFormSupplementaryInfo.js, src/routes/Agreements.js
=> Release v2.5.0

test/ui-testing/notes-crud.js
Wait for the Note types pane to render
=> Wait for the Note types pane to render

test/ui-testing/notes-crud.js
Add waitUntilNetworkIdle after editing a note
=> Add waitUntilNetworkIdle after editing a note

translations/ui-agreements/ar.json
=> Update translation strings as of 20190627T152539

src/components/AgreementSections/Header.js
=> Fixed agreement status label in header

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/zh_CN.json
=> Update translation strings as of 20190703T132726

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/zh_CN.json
=> Update translation strings as of 20190709T154346

test/ui-testing/po-lines.js
Update integration test based on addition of `isSingleSelect` prop in ui-plugin-find-po-line
=> PO Lines: Update test for single-select plugin

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/zh_CN.json
=> Update translation strings as of 20190711T172340

src/components/AgreementSections/Lines.js, src/components/views/Agreement.js, src/components/views/Package.js, src/components/views/Title.js
- Moved **Notes** accordions in eresource views.
- Move Agreement Lines accordion in agreement view.
- Removed Finance accordion in agreement view.
=> ERM-318: Reorganize agreement and eresource accordions

src/components/views/AgreementForm.js, test/ui-testing/agreement-crud.js, test/ui-testing/basket.js, test/ui-testing/custom-coverage.js, test/ui-testing/docs.js, test/ui-testing/ekb-int.js, test/ui-testing/external-licenses.js, test/ui-testing/hide-eresources-func.js, test/ui-testing/interfaces.js, test/ui-testing/license-terms.js, test/ui-testing/linked-licenses.js, test/ui-testing/orgs.js, test/ui-testing/po-lines.js, test/ui-testing/supplement.js
Code is trivial, tests took a bit more 😆
=> ERM-340: Open accordions by default

src/components/AgreementFilters/AgreementFilters.js
Just a little bug, most of the guts were already there.
=> ERM-339: Show "clear tag filters" button

package.json
Orders 7.0 was released. [The breaking changes don't affect us.](https://issues.folio.org/browse/MODORDERS-275)
=> ERM-350: Support Orders 7.0

src/components/views/AgreementForm.js, translations/ui-agreements/en.json
`Update agreement` -> `Save & close`
`Create agreement` -> `Save & close`
=> ERM-308: Update AgreementForm btn labels

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/zh_CN.json
=> Update translation strings as of 20190809T200806

package.json, src/components/UsageDataProvidersFieldArray/UsageDataProvidersFieldArray.js
[Fixed capitalization here.](https://github.com/folio-org/stripes-erm-components/pull/101/files#diff-cf8293896328e4786ff94f58f8e4820aR63)
=> Update onMarkForDeletion capitalization

CHANGELOG.md, package.json, src/settings/index.js
=> Release 3.1.0

src/components/BasketList/BasketList.js, src/components/EResourceSections/PackageContents.js
fix CoverageStatements in PackageContents and BasketList
=> ERM-372 Display coverage in e-resources / e-resources in package

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/zh_CN.json
=> Update translation strings as of 20190903T134424

src/components/LicensesFieldArray/LicensesFieldArray.js
adjust status and notes field width
=> ERM-439 Width of 'Status (this agreement)' field

CHANGELOG.md, package.json
Add support for `invoice` interface `2.0`
=> Release 3.2.4

CHANGELOG.md, package.json, src/components/AgreementSections/Info.js, src/components/AgreementSections/Licenses.js, src/components/AgreementSections/LinkedLicenses.css, src/components/AgreementSections/LinkedLicenses.js, src/components/views/Agreements.js, src/components/views/EResources.js
- Update stripes dependency to 2.10.1
- Update CHANGELOG
=> Preserve line-break characters for paragraph fields, refs ERM-444

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/zh_CN.json
=> Update translation strings as of 20190918T144452

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/zh_CN.json
=> Update translation strings as of 20190927T125508

src/components/EResourceSections/TitleInfo.js
Apply large headline styling to all the e-resources titles
=> Apply large headline to books and journals, refs ERM-472

package.json, src/components/AgreementSections/FormLicenses.js, src/components/LicensesFieldArray/AmendmentsFieldArray.js, src/components/LicensesFieldArray/LicensesFieldArray.js, src/components/views/AgreementForm.js
Use the new warning pattern with `setFieldData`
=> RFF Amendments: Migrate warning to new RFF style

package.json
Bump versions accepted of `invoice` and `orders`
=> ERM-502: Support new acquisitions interfaces

src/components/views/Agreements.js, src/components/views/EResources.js, src/index.js, src/routes/AgreementsRoute.js, src/routes/EResourcesRoute.js
Agreements and EResources now have correct colouring on selected rows
=> PR for ERM-512

src/components/UsageDataProvidersFieldArray/UsageDataProvidersFieldArray.js
Added tooltip to bin icon for removing usage data provider
=> PR for ERM-520

package.json, src/components/EResourceSections/AcquisitionOptions.js, src/components/EResourceSections/Agreements.js, src/components/EResourceSections/PackageContents.js, src/components/views/Agreement.js, src/components/views/EResource.js, src/components/views/Package.js, src/components/views/Title.js, src/routes/AgreementCreateRoute.js, src/routes/AgreementEditRoute.js, test/ui-testing/agreement-notes.js, test/ui-testing/custom-coverage.js
- Moved **Agreements for E-resource** sections into accordions
- Switched to generic `LoadingPane` component.
=> ERM-491: Move Ags for EResource into accordion

src/components/AgreementSections/FormRelatedAgreements.js, src/components/RelatedAgreementsFieldArray/RelatedAgreementsFieldArray.js, src/constants/agreementRelationshipTypes.js, translations/ui-agreements/en.json
Uses new `MessageBanner` component added in https://github.com/folio-org/stripes-components/pull/1082
=> Related Agreements: Add banner to summarise relationship

src/components/RelatedAgreementsFieldArray/RelatedAgreementsFieldArray.js
switch to 'onUpdateField' in RelatedAgreementsFieldArray
=> ERM-548: Do not wipe data from linked Agreement fields when using 'Replace agreement'

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/he.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/ja.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/ru.json, translations/ui-agreements/zh_CN.json, translations/ui-agreements/zh_TW.json
=> Update translation strings as of 20191127T181804

src/components/AgreementLinesFieldArray/POLineField.js
Needs to be merged after https://github.com/folio-org/stripes-acq-components/pull/135
=> Pass trigger button ref to <Button /> component, refs ERM-620

CHANGELOG.md, src/components/AgreementLinesFieldArray/POLineField.js, src/components/AgreementLinesFieldArray/POLinesFieldArray.js, src/components/AgreementSections/FormInfo.js, src/components/LicensesFieldArray/LicenseField.js, src/components/RelatedAgreementsFieldArray/RelatedAgreementField.js, src/components/UsageDataProvidersFieldArray/UsageDataProviderField.js, src/components/utilities/validators.js, src/routes/AgreementEditRoute.js, src/routes/AgreementViewRoute.js, test/ui-testing/interfaces.js, test/ui-testing/orgs.js
- Lots of autofocus fixes using the technique of setting the `name` of a `<button>` which I learned working on https://github.com/folio-org/stripes-erm-components/pull/161
- Updated tests to handle refactored OrganizationsFieldArray in https://github.com/folio-org/stripes-erm-components/pull/167
- Started sorting agreement lines by name (best effort from the backend, since packages still sort above titles)
=> Keyboard navigation improvements and misc fixes

src/components/UsageDataProvidersFieldArray/UsageDataProviderField.js, translations/ui-agreements/en.json
Changes made to usage data provider card to bring it into line with organisations card
=> PR For ERM-604

src/components/AgreementSections/CoveredEResourcesList.js
Add margin-top and bottom to the rendered Headline
=> Add margin for Eresources covered Headline, refs ERM-596

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/he.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/ja.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/ru.json, translations/ui-agreements/zh_CN.json, translations/ui-agreements/zh_TW.json
=> Update translation strings as of 20200110T211826

src/components/AddToBasketButton/AddToBasketButton.js, test/ui-testing/linked-license-warnings.js, test/ui-testing/linked-licenses.js
adjust linked-licenses and linked-license-warnings tests
=> ERM-454 Display the Amendment record when a new Amendment is added

src/components/EResourceCount/EResourceCount.js
changed `EResourceCount` to get counts from the newly provided resourceCount. (Until backend PR is merged this will just continue to display '1' as before.)
=> PR for Front End part of ERM-507

src/components/AgreementSections/CoveredEResourcesList.js
change eresources all filter in CoveredEresources
=> refs ERM-680

test/ui-testing/orgs.js
=> fix orgs test refs ERM-692

package.json, src/settings/components/SupplementaryPropertiesConfigForm.js, src/settings/index.js, src/settings/routes/PickListSettings.js, src/settings/routes/PickListValueSettings.js, src/settings/routes/SupplementaryPropertiesConfigRoute.js, src/settings/routes/index.js, test/ui-testing/pick-lists.js, translations/ui-agreements/en.json
refs ERM-714
- Added PickLists settings to Agreements settings
- Tests for pickLists
=> Support pick lists as type for Agreement Supplementary properties

src/routes/AgreementCreateRoute.js, src/routes/AgreementEditRoute.js, translations/ui-agreements/en.json
- added callouts to agreement creation and update, translations
=> ERM-726: Display callouts upon agreement creation/update

translations/ui-agreements/en.json, translations/ui-agreements/en_US.json
Changed from "Create agreement" to "New agreement"
=> ERM-758: Create agreement title change

src/components/views/Agreements.js, src/routes/AgreementCreateRoute.js, src/routes/AgreementEditRoute.js
This PR converts the `onSubmit` handler to an async function by returning a Promise out of it. React Final Form will now set the various submitting/etc `formState` props based on the Promise's status.
=> Disable Save button on form submission

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/he.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/ja.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/ru.json, translations/ui-agreements/ur.json, translations/ui-agreements/zh_CN.json, translations/ui-agreements/zh_TW.json
=> Update translation strings as of 20200312T133304

translations/ui-agreements/ru.json
=> Update translation strings as of 20200314T132532

src/routes/AgreementEditRoute.js
=> ERM-427 No way of fetching agreement entitlements sorted by name

src/components/AgreementSections/CoveredEResourcesList.js, src/components/AgreementSections/LinesList.js
Small changes to the way we render:
- Empty access start/end dates
- Type column header
=> ERM-781 ERM-815: Agreement line MCL tweaks

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/he.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/ja.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/ru.json, translations/ui-agreements/ur.json, translations/ui-agreements/zh_CN.json, translations/ui-agreements/zh_TW.json
=> Update translation strings as of 20200331T152557

src/components/AgreementSections/UsageData.js, translations/ui-agreements/en.json
=> ERM-496: Display message when user cannot view ERM Usage provider

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/he.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/ja.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/ru.json, translations/ui-agreements/ur.json, translations/ui-agreements/zh_CN.json, translations/ui-agreements/zh_TW.json
=> Update translation strings as of 20200403T124750

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/he.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/ja.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/ru.json, translations/ui-agreements/ur.json, translations/ui-agreements/zh_CN.json, translations/ui-agreements/zh_TW.json
=> Update translation strings as of 20200406T162815

translations/ui-agreements/pt_BR.json
=> Update translation strings as of 20200409T134057

Jenkinsfile, src/settings/routes/PickListValueSettings.js, test/bigtest/helpers/monkey-patch-run.js, test/bigtest/helpers/turn-off-warnings.js, test/bigtest/index.js, test/bigtest/tests/clone-agreement-test.js, test/bigtest/tests/package-content-test.js
Inspired by https://github.com/folio-org/ui-users/pull/1285
=> Turn tests back on by monkey-patching bigtest

src/components/EResourceSections/Agreements.js, src/components/EResourceSections/PackageInfo.js
Need to use [`PACKAGE`](https://github.com/folio-org/ui-erm/blob/17085a6dd46983a83a4109189554d4dffedfd3bb/src/constants/resourceClasses.js#L2) and not `PKG`
=> Fixed bug where undefined resource class was used

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/he.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/ja.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/ru.json, translations/ui-agreements/ur.json, translations/ui-agreements/zh_CN.json, translations/ui-agreements/zh_TW.json
=> Update translation strings as of 20200521T142352

translations/ui-agreements/es_419.json
=> Update translation strings as of 20200528T173426

src/components/AgreementLineSections/FormInfo.js, src/components/AgreementLineSections/Info.js
- Checkbox usage didn't need to be so complicated...artifact from previous work.
- Four column layout in view mode as well to match layout in edit mode.
- Display active to/from dates based on activeTo/activeFrom properties
=> ERM-923 ERM-934: Tweaks

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/he.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/ja.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/ru.json, translations/ui-agreements/ur.json, translations/ui-agreements/zh_CN.json, translations/ui-agreements/zh_TW.json
=> Update translation strings as of 20200604T202430

translations/ui-agreements/fr_FR.json
=> Update translation strings as of 20200608T134746

translations/ui-agreements/de.json, translations/ui-agreements/zh_TW.json
=> Update translation strings as of 20200618T161121

translations/ui-agreements/ru.json
=> Update translation strings as of 20200624T130324

translations/ui-agreements/de.json
=> Update translation strings as of 20200723T031126

src/components/AgreementLinesFieldArray/AgreementLineField.js, src/components/AgreementSections/LinesList.js, src/components/BasketList/BasketList.js, src/components/PackageCard/PackageCard.js, src/components/TitleCard/MonographResourceInfo.js, src/components/TitleCard/SerialResourceInfo.js, src/components/TitleCardExternal/TitleCardExternal.js, src/components/views/EResources.js, test/bigtest/interactors/title-card.js, test/bigtest/tests/agreement-line-edit-test.js, test/bigtest/tests/resources/monographResource.js, test/bigtest/tests/resources/serialResource.js, test/bigtest/tests/title-card-test.js, translations/ui-agreements/en.json
* change type to publicationType for resources in views and tests
=> ERM-943 Separate ERM 'publication type' from 'type'

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/he.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/ja.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/ru.json, translations/ui-agreements/ur.json, translations/ui-agreements/zh_CN.json, translations/ui-agreements/zh_TW.json
=> Update translation strings as of 20200804T150835

src/components/EResourceFilters/EResourceFilters.js, src/routes/EResourcesRoute.js
=> ERM-944 Search by publication type

src/components/AgreementFilters/AgreementFilters.js, src/routes/AgreementsRoute.js, translations/ui-agreements/en.json
refs ERM-1043
* separate organisation and role filter
refs ERM-1044
* add description to agreement search
=> ERM-1043 separate organisation and role filter

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/he.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/ja.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/ru.json, translations/ui-agreements/ur.json, translations/ui-agreements/zh_CN.json, translations/ui-agreements/zh_TW.json
=> Update translation strings as of 20200806T130626

translations/ui-agreements/en.json
Changed from `Display "Suppress from discovery" on` to `Display "Suppress from discovery" setting on`
=> ERM-1064: Slight translations tweak

translations/ui-agreements/ar.json, translations/ui-agreements/ca.json, translations/ui-agreements/da.json, translations/ui-agreements/de.json, translations/ui-agreements/en_GB.json, translations/ui-agreements/en_SE.json, translations/ui-agreements/en_US.json, translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/fr.json, translations/ui-agreements/fr_FR.json, translations/ui-agreements/he.json, translations/ui-agreements/hu.json, translations/ui-agreements/it_IT.json, translations/ui-agreements/ja.json, translations/ui-agreements/pt_BR.json, translations/ui-agreements/pt_PT.json, translations/ui-agreements/ru.json, translations/ui-agreements/ur.json, translations/ui-agreements/zh_CN.json, translations/ui-agreements/zh_TW.json
=> Update translation strings as of 20200811T193833

translations/ui-agreements/fr_FR.json
=> Update translation strings as of 20200904T163521

src/components/CoverageFieldArray/CoverageFieldArray.js, translations/ui-agreements/en.json
=> add new translation emptyAccordion.lineCustomCoverage, refs erm-1129

src/components/AgreementSections/LinesList.js, src/components/EResourceSections/Agreements.js, src/components/EResourceSections/PackageContents.js, src/components/EntitlementsAgreementsList/EntitlementAgreementsList.js
* revert changes from erm-780: sort agreement lines list name, activeFrom, activeTo column
* revert changes from erm-1141: sort in package view
=> ERM-1161 Remove frontend sorting in MCLs

src/routes/EResourceViewRoute.js
Reverts folio-org/ui-agreements#626
=> Revert "Check isPending flag on all okapi resources before loading eresource pane"

translations/ui-agreements/pt_BR.json
=> Update translation strings as of 20201008T220807

translations/ui-agreements/es.json, translations/ui-agreements/es_419.json, translations/ui-agreements/es_ES.json, translations/ui-agreements/ja.json
=> Update translation strings as of 20201102T140138

src/components/views/AgreementForm.js, src/routes/AgreementCreateRoute.js, src/routes/AgreementEditRoute.js, src/routes/AgreementsRoute.js
* add perPage param to agreement routes
=> ERM-1192 Load 100 values from user definable pick lists in agreements

CHANGELOG.md, test/bigtest/helpers/discovery.js
Rename instance-bulk to inventory-record-bulk in the scope of the [UIIN-1368](https://issues.folio.org/browse/UIIN-1368).
=> UIIN-1368: Rename instance-bulk to inventory-record-bulk

src/components/POLineCard/POLineCard.js, src/components/utilities/urls.js, test/bigtest/interactors/po-line-card.js, test/bigtest/tests/po-line-card-test.js, translations/ui-agreements/en.json
Added inventory link to POL Card when instanceId attached.
Amended tests/added translations
=> ERM-1228: Add POL/Inventory Instance details to Agreement Line display

src/components/CoverageFieldArray/CoverageFieldArray.js, src/components/CoverageFieldArray/CoverageFieldArray.test.js
Added test coverage for CoverageFieldArray, testing the warning messages, submittal and rendering
=> ERM-1387: Add test coverage for <CoverageFieldArray.js>

CHANGELOG.md, src/components/views/Agreement.js, test/ui-testing/agreement-crud.js, test/ui-testing/basket.js, test/ui-testing/contacts.js, test/ui-testing/custom-coverage.js, test/ui-testing/docs.js, test/ui-testing/eusage.js, test/ui-testing/hide-eresources-func.js, test/ui-testing/interfaces.js, test/ui-testing/license-terms.js, test/ui-testing/linked-license-warnings.js, test/ui-testing/linked-licenses.js, test/ui-testing/orgs.js, test/ui-testing/po-lines.js, test/ui-testing/related-agreements.js
add comment in nightmare tests
=> remove edit button in agreement view, refs ERM-693

src/index.js, translations/ui-agreements/en.json
* use KeyboardShortcutsModal and NavList component in App
=> ERM-1642 display the keyboard shortcuts modal

src/components/AgreementSections/Info.js
* add conditional rendering of licenseNote in agreements view info section
=> ERM-1750 General License note not displayed in Agreements view

src/components/AgreementLineSections/FormEresource.js, src/components/BasketSelector/BasketSelector.js, translations/ui-agreements/en.json
* add InfoPopover, Tooltip to BasketSelector
* tweak onAdd callback
* add setFieldData error for linkedResource field
=> ERM-1145 new agreement line UX improvements

src/components/AgreementLineSections/Info.js, src/components/AgreementSections/Info.js
=> ERM-1231 Add date created/last updated metadata to Agreements

src/components/OpenBasketButton/OpenBasketButton.test.js, src/components/OpenBasketButton/testResources.js
* add test for OpenBasketButton component, refs ERM-1282
=> ERM-1282 Add test coverage for ui-agreements OpenBasketButton

src/settings/GeneralSettingsForm.test.js
=> Test coverage for GeneralSettingsForm, ref ERM-1489

src/settings/components/SuppressFromDiscoveryFields/SuppressFromDiscoveryFields.js, src/settings/components/SuppressFromDiscoveryFields/SuppressFromDiscoveryFields.test.js
* add test for SuppressFromDiscoveryFields component
* remove normalize prop from Checkbox Field components in SuppressFromDiscoveryFields component
=> ERM-1494 Add test coverage for ui-agreements SuppressFromDiscoveryFields

src/routes/EResourcesRoute/index.js
Filled in an empty index.js file that was causing errors
ERM-1948
=> fix: Index

src/routes/AgreementViewRoute/AgreementViewRoute.js
Added an initial sort by "type" to agreement line fetch in agreement view route
ERM-1931
=> feat: Sort

pr-tests.yml
Test PR to see if actions workflow does anything
=> Chore: pr protections GitHub actions

src/routes/AgreementViewRoute/AgreementViewRoute.js
change `null` to `{}` in interfaces manifest return query statement
=> ERM-1973 Organization interface data hidden

src/routes/AgreementViewRoute/AgreementViewRoute.js
* store credentials in an array constant per agreement to not loose once fetched ones
=> ERM-1974 Organization interface credentials malfunction

src/components/AgreementLinesFieldArray/AgreementLinesFieldArray.test.js, src/components/AgreementSections/CoveredEResourcesList/CoveredEResourcesList.test.js, src/components/views/Agreements/Agreements.test.js, src/components/views/EResources/EResources.test.js, src/components/views/Platforms/Platforms.test.js
Disabled proptypes for all instances of IfEResourcesEnabled mock
=> chore: Linting

src/setUpRegistry.js
* set up registry entry for `ermPackage` resource
=> ERM-1990 Add hyperlink to ERM Comparison comparison points

src/routes/AgreementViewRoute/AgreementViewRoute.js
Fetch order lines only for those agreementLines we've already fetched
=> fix: OrderLines

package.json, src/components/EResourceSections/PackageInfo/PackageInfo.test.js, src/routes/AgreementViewRoute/AgreementViewRoute.js
Fixed order line fetching so that when a new POLine is created or removed, the subsequent render of the agreement itself reflects that
=> fix: Order line fetch

package.json
Added permissions to frontend to reflect backend AppSetting view/manage perms
ERM-1940
=> chore: AppSettings Permissions

CHANGELOG.md, package.json
Bumped version to 8.2.0, added changelog section
ERM-2003
=> chore: Version Bump

package.json
Bump version of stripes-kint-components to 2.1.0
=> chore: Stripes-kint-components

package.json, src/settings/components/AgreementsCustomProperties/AgreementsCustomProperties.js, translations/ui-agreements/en.json
Bumped version of stripes-kint-components to take advantage of the new support for date type custprops and retired custprops
Refs ERM-778, ERM-2018, ERM-2044
=> feat: Changelog enhancements

src/components/EResourceSections/PackageInfo/PackageInfo.js, src/components/EResourceSections/PackageInfo/PackageInfo.test.js
* add FormattedMessage for all KeyValue labels in PackageInfo component
* add translationsProperties to empty fields test in PackageInfo.test
=> ERM-2086 Labels in PackageInfo component are not translatable

src/components/utilities/getRefdataValuesByDesc.js, src/components/utilities/index.js, src/routes/AgreementCreateRoute/AgreementCreateRoute.js, src/routes/AgreementEditRoute/AgreementEditRoute.js, src/routes/AgreementsRoute/AgreementsRoute.js, src/routes/EResourcesRoute/EResourcesRoute.js
Moved utility function to stripes-erm-components to cut down on code reuse
=> refactor: getRefdataValuesByDesc

package.json
Bumped kint-component dependency
ERM-2158, ERM-2159
=> build: Kint-components

src/components/EResourceSections/PackageIdentifiers/PackageIdentifiers.js
Neatly refactored PackageIdentifier code, so that it now dynamically adds columns to a row if the value exists.
ERM-2120
=> fix: Ids only show up if they exist

src/hooks/useAgreementsRefdata.js
Refactored useAgreementsRefdata to make slightly more useful down the road
=> refactor: useAgreementsRefdata

package.json, src/settings/components/AgreementsCustomProperties/AgreementsCustomProperties.js, translations/ui-agreements/en.json
Added translations for pick list and pick list (multi-select) to override refdata and refdata (multi-select)
ERM-2217
=> chore: Translations

src/routes/AgreementCreateRoute/AgreementCreateRoute.js, src/routes/AgreementEditRoute/AgreementEditRoute.js, src/routes/AgreementViewRoute/AgreementViewRoute.js, src/routes/AgreementsRoute/AgreementsRoute.js
Changed namespacing for Agreement queries so caches can be shared between apps
refs ERM-2227, ERM-2278
=> refactor: Query Namespace

src/components/AgreementLinesFieldArray/AgreementLinesFieldArray.js, src/components/AgreementPeriodsFieldArray/AgreementPeriodsFieldArray.js, src/components/CoverageFieldArray/CoverageFieldArray.js, src/components/LicensesFieldArray/AmendmentsFieldArray.js, src/components/LicensesFieldArray/LicensesFieldArray.js, src/components/POLinesFieldArray/POLinesFieldArray.js, src/components/RelatedAgreementsFieldArray/RelatedAgreementsFieldArray.js, src/components/UsageDataProvidersFieldArray/UsageDataProvidersFieldArray/UsageDataProvidersFieldArray.js
* convert several components to functional
* replace withKiwtFieldArray with useKiwtFieldArray
=> ERM-2234 Replace withKiwtFieldArray with useKiwtFieldArray

src/components/AgreementFilters/AgreementFilters.test.js, src/components/views/Agreement/Agreement.test.js, src/routes/AgreementCreateRoute/AgreementCreateRoute.test.js, src/routes/AgreementEditRoute/AgreementEditRoute.test.js, src/routes/AgreementsRoute/AgreementsRoute.test.js, src/settings/routes/PickListSettings.test.js, src/settings/routes/PickListValueSettings.test.js
switched to new way of mocking kint components so it's easier to add component-by-component mocks
=> test: MockKintComponents

CHANGELOG.md
Added changelog section for patch release
ERM-2281
=> docs: Post-Release 8.2.1

CHANGELOG.md
Added changelog section for 8.2.2 release
refs ERM-2302
=> docs: CHANGELOG

package.json
* add version 16.0 to package.json
=> ERM-2283 Upgrade Users interface to 16.0

src/components/IdentifierReassignmentForm/DestinationTitlePreview/DestinationTitlePreview.js, src/components/styles.css
Refactor to use NewBox component from erm-components
=> refactor: NewBox

src/routes/AgreementLinesRoute/AgreementLinesRoute.js
Added a check for whether we have any search terms or filters selected, and via that we set the "loaded" prop in the source to show a filter splash screen
ERM-2339
=> feat: Idle

README.md
Bumped copyright in README to 2022
=> chore: Bump copyright

src/routes/AgreementLineEditRoute/AgreementLineEditRoute.js
* remove postAgreementLine block
* move if/else decision inside putAgreementLine block
=> ERM-2356 Add an option to "create another" agreement line

src/components/views/AgreementForm/AgreementForm.js, src/components/views/EResources/EResources.js, src/components/views/UrlCustomizerForm/UrlCustomizerForm.js, translations/ui-agreements/en.json
Fixes to ensure release has as few console errors etc as possible
=> chore: Fixes for release

src/components/AgreementSections/Lines/Lines.test.js, src/components/EResourceCount/EResourceCount.js, translations/ui-agreements/en.json
Added missing translations to ui-agreements.
Tweaked tests. Also tweaked propTypes to avoid console errors
ERM-2399
=> fix: Added missing translations

src/routes/AgreementsRoute/AgreementsRoute.test.js
Previously we mocked Selection, this is unnecessary
=> test: Removed unnecessary mock

package.json, src/components/EResourceSections/PackageInfo/PackageInfo.js, src/components/EResourceSections/PackageInfo/PackageInfo.test.js
Implemented id on FormattedDateTime and utilised new FormattedDateTime interactor in tests
ERM-2463
=> test: FormatteddateTime

src/components/CoverageFieldArray/CoverageFieldArray.test.js, src/components/IdentifierReassignmentForm/DestinationTitlePreview/DestinationTitlePreview.js, src/components/LicenseAmendmentList/LicenseAmendmentList.js, src/components/POLineCard/POLineCard.test.js, src/components/PlatformSections/PlatformUrlCustomization/PlatformUrlCustomization.js, src/components/PlatformSections/PlatformUrlCustomization/testResources.js, src/components/views/AgreementLineForm/AgreementLineForm.js, src/components/views/AgreementLineForm/AgreementLineForm.test.js, src/components/views/AgreementLineForm/AgreementLineFormIfEresourcesDisabled.test.js, src/components/views/AgreementLines/AgreementLines.test.js, src/components/views/Agreements/Agreements.test.js, src/components/views/Platforms/Platforms.test.js, src/components/views/UrlCustomizer/UrlCustomizer.js
Gone through all test warnings and solved them so yarn test is clean in the console
=> test: Fixed test warnings

src/constants/endpoints.js, src/routes/TitlesRoute/TitlesRoute.js
Add titles electronic endpoint constant, making use of new endpoint from ERM-2510
ERM-2511
=> feat: Electronic endpoint

src/hooks/useBasketStore.js
=> ERM-2574 fix deprecated default export from 'zustand'

CHANGELOG.md, package.json
Upgrade `stripes-acq-components` to `v4`
=> ERM-2613 Remove unneeded `react-redux`.

CHANGELOG.md
Updated CHANGELOG, ensured dependencies are up to date
ERM-2502
=> chore: Release 9.0.0

src/components/views/Package/Package.js, src/routes/PackagesRoute/PackagesRoute.js
Removed unnecessary filter block from packages route, small tweak to view component to fix boolean logic
refs (In a very roundabout way) ERM-2630
=> chore: Packages tweaks

src/components/AgreementSections/Info/Info.js, src/components/AgreementSections/Info/Info.test.js
* use join method for concatenate labels
=> ERM-2612 fix change request

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
Updated github workflows to allow use of multiple cores while running jest tests
=> build: Github wokflows

CHANGELOG.md, src/components/EResourceKB/EResourceKB.js, src/components/EResourceKB/EResourceKB.test.js, src/components/EResourceSections/AcquisitionOptions/AcquisitionOptions.test.js, src/components/PackageFilters/PackageFilters.js, src/components/PackageFilters/testResources.js, src/routes/PackagesRoute/PackagesRoute.js
* fetch distinct dataSources from packages in PackagesRoute
* use these values for source filter in PackageFilters
* remove remoteKb.id based filter
* fix EResourceKB component to use source instead of remoteKb
* fix tests
* edit CHANGELOG
=> ERM-2920 Replace 'External data source' search

src/components/IdentifierReassignmentForm/DestinationTitleIdentifierField/DestinationTitleIdentifierField.js, src/components/LicensesFieldArray/tests/LicensesFieldArray.test.js, src/routes/AgreementEditRoute/AgreementEditRoute.js, src/routes/AgreementLineEditRoute/AgreementLineEditRoute.js
Cleanup of some sonarlint "problems"
refs ERM-2421 (Only insofar as that brought them to my attention)
=> chore: Code cleanup

src/components/AgreementSections/ContentTypesFieldArray/ContentTypesFieldArray.js
Make use of new usePrevious hook from erm-components
=> feat: usePrevious

src/routes/AgreementEditRoute/AgreementEditRoute.js, src/routes/AgreementViewRoute/AgreementViewRoute.js
Removed expandItems=false
[ERM-2992](https://issues.folio.org/browse/ERM-2992)
=> ERM-2992, Removed expandItems=false

src/components/views/Packages/Packages.js, src/components/views/Titles/Titles.js, src/routes/AgreementCreateRoute/AgreementCreateRoute.js
* add workaround to AgreementCreateRoute
=> ERM-3038 Creating adding an eHolding resource to a new agreement fails

src/components/views/Platforms/Platforms.js, src/routes/PlatformsRoute/PlatformsRoute.js
Implemented Next/Prev pagination
[ERM-2054](https://issues.folio.org/browse/ERM-2054)
=> ERM-2054, Platforms Tab - Implement MCL Next/Previous pagination

CHANGELOG.md
=> ERM-3107 ui-agreements release

CHANGELOG.md, package.json, src/components/RelatedAgreementsFieldArray/RelatedAgreementField.js
* Bumped version to 11.0.0
* Updated changelog
* Changed interface dependencies (erm 7, licenses 6)
* Bumped other dependencies
* Fixed deprecated prop use
ERM-3107
=> chore: Release 11.0.0

.github/workflows/stuck-license-cla.yml
Don't need a new comment with every push to the PR
=> chore: Only run the License CLA once per PR

CHANGELOG.md
Added changelog section for post 11.0.3 release
=> chore: Post release 11.0.3

GUIDANCE.md, LICENSE
Updated license and added guidance.md file
=> ERM-3375: Update module license and guidance

CHANGELOG.md, package.json, src/components/AgreementContentFilter/AgreementContentFilter.test.js, src/components/AgreementSections/Lines/Lines.test.js
Updated CHANGELOG and dependencies, fixed a couple of errant tests
ERM-3264
=> chore: Release 11.1.0

CHANGELOG.md
Added changelog section reflected in release 11.1.1
=> chore: Post release 11.1.1

src/components/views/Agreement/Agreement.js, src/hooks/useAgreementsHelperApp.js
Pulled Tags stuff in from kint-components instead of passthrough via erm-components
=> refactor: Tags

CHANGELOG.md, package.json
Bumped dependencies and added CHANGELOG.md section to reflect release changes
ERM-3412
=> chore: Release 12.0.0

CHANGELOG.md, package.json
Bumped version to 12.1.0 and added new CHANGELOG.md section
=> chore: Post release 12.0.0

src/components/EResourceSections/PackageInfo/PackageInfo.test.js, src/components/EResourceSections/PackageSyncronisingValue/PackageSyncronisingValue.js
* fix if condition
* extend test
=> ERM-3670 When package 'syncContentsFromSource' is not set, display with a '-'

CHANGELOG.md
Added CHANGELOG.md section reflected in 12.0.1 release
=> chore: Post release 12.0.1

src/components/OpenBasketButton/OpenBasketButton.js, src/components/views/Basket/Basket.js
* add from state to OpenbasketButton history
* use that state in Basket to determine in putAgreement where we came from
* fix prop tyes object errors in Basket
* get rid of PropTypes in OpenBasketButton
=> ERM-3673 Agreements: query mixup in Agreements and Local KB package search box

CHANGELOG.md
Added CHANGELOG.md section reflected in release 12.0.2
=> docs: Post release 12.0.2

src/index.js, src/routes/GokbRoute/GokbRoute.js, src/routes/GokbRoute/index.js, translations/ui-agreements/en.json
Added initial implementation of GOKb route
ERM-3761
=> ERM-3761: GOKb Route

docs/gokb-search-v1.json
Consolidated gokb config changes made iteratively by Claudia and Monireh into a single branch, whilst also removing the still in-development view property
=> refactor: Consolidated GOKb config changes

docs/gokb-search-v1.json
Added GOKB gonfig view property, currently includes title information and extended title information sections
ERM-3724
=> ERM-3724: GOKB Config View

src/routes/AgreementCreateRoute/AgreementCreateRoute.js, src/routes/AgreementEditRoute/AgreementEditRoute.js
* add normalize helper function
* edit routes
* fix PropTypes object not allowed warning
=> ERM-3820 On creating/editing an agreement, do not POST a 'claim' for access policies unless there are changes
