folio-org/ui-agreements

package.json
src/components/Tabs/Tabs.js
src/components/ViewAgreement/Sections/AgreementInfo.js
src/components/ViewAgreement/Sections/AgreementLines.js
src/components/ViewAgreement/Sections/AssociatedAgreements.js
src/components/ViewAgreement/Sections/Eresources.js
src/components/ViewAgreement/Sections/License.js
src/components/ViewAgreement/Sections/LicenseBusinessTerms.js
src/components/ViewAgreement/Sections/Organizations.js
src/components/ViewAgreement/ViewAgreement.js
src/components/ViewKB/ViewKB.js
src/components/ViewTitle/ViewTitle.js
src/routes/Agreements.js
src/routes/KBs.js
src/routes/Titles.js

Switched to using the top-level imports for Stripes modules as a result of the work in https://github.com/folio-org/stripes-smart-components/pull/256

Cleaned up import statements

---

src/ERM.js
src/components/Tabs/Tabs.js
src/routes/Agreements.js
src/routes/KBs.js
src/routes/Titles.js

Paging was busted on the Titles route because:
- It kept paging up and up without end, past page 102 etc.
- The first two pages were the same.
Fixed it by:
- Resetting the `resultCount` when navigating to a new page via Tabs.
- Using the `offset` rather than `page` parameter.

Fixed paging requests for /titles

---

package.json
src/components/Agreements/ViewAgreement/Sections/AgreementLines.js
src/routes/Agreements.js
src/routes/KBs.js
translations/ui-erm/en.json

There are a couple of outstanding bugs with using function-type path's in a connected component's manifest: [STCON-48](https://issues.folio.org/browse/STCON-48) and [STCON-49](https://issues.folio.org/browse/STCON-49)
I'm switching these components over to use a traditional string path to avoid that, and also since it's not really necessary for our use case to have function paths - the only things we're really changing here are the `params` anyway.

Switched to using string-type paths for manifest

---

src/components/Agreements/ViewAgreement/Sections/VendorInfo.css
src/components/Agreements/ViewAgreement/Sections/VendorInfo.js
src/components/Agreements/ViewAgreement/Sections/index.js
src/components/Agreements/ViewAgreement/ViewAgreement.js
translations/ui-erm/en.json

The Vendor Info is the one that's at the top of the agreement detail view and stays visible as the user scrolls down.
`VendorInfo.css` has the CSS to accomplish that, but I'll be chatting with some of the stripes-components folks to see whether it makes sense to turn this into a component itself.

Agreements: Vendor Info

---

src/ERM.js
src/routes/Agreements.js
src/routes/KBs.js
src/routes/Titles.js

`ERM` defining the `resultCount` resource at the top level initialized it before `SearchAndSort` in the various route components could. Removed it from `ERM` and let the routes initialise it themselves.

Fix resultCount bug

---

src/routes/Agreements.js
src/routes/KBs.js
src/routes/Titles.js
src/util/getSASParams.js

Refactored query param generation; it's now all done in `getSASParams.js`. 
Text searching continues to work, and I added sorting of columns as well. Sorting is not i18n-friendly atm due to [this bug on SearchAndSort](https://issues.folio.org/browse/STSMACOM-93). SAS will be rejigged in the next month or two so hopefully this will get fixed during that.

Added generic query param generator for SAS record fetching

---

src/components/Agreements/ViewAgreement/Sections/AgreementInfo.js
src/components/Agreements/ViewAgreement/Sections/AssociatedAgreements.js
src/components/Agreements/ViewAgreement/Sections/Eresources.js
src/components/Agreements/ViewAgreement/Sections/License.js
src/components/Agreements/ViewAgreement/Sections/LicenseBusinessTerms.js
src/components/Agreements/ViewAgreement/Sections/Organizations.js
src/components/EResources/ViewEResource/Sections/AcquisitionOptions.js
src/components/EResources/ViewEResource/Sections/EResourceInfo.js

Basically just minimizing our dependence on the `stripes` prop. If we're only consuming the `intl` part of `stripes`, we can get that directly from `react-intl`. 
I can't convert all our usage to this just yet because stripes-connected components have issues with injected `intl`. The argument can be made that we should split up any component that requires both `intl` and `connect` into presentation and container components, but that's not a job for today.

Switched components to direct dep on react-intl where possible

---

src/ERM.js
src/components/EResources/ViewEResource/Sections/EResourceAgreements.js
src/components/EResources/ViewEResource/Sections/EResourceInfo.js
src/components/EResources/ViewEResource/ViewEResource.js
src/routes/Agreements.js
src/routes/EResources.js
translations/ui-erm/en.json

- Updated the E-resources section to the new `/erm/resource/*` paths.
- Fixed a paging bug.
- Query params specify `perPage` again and use the `offset` param rather than the `page` param.
- In the E-resource details pane, show the agreements for the selected e-resource.
- Using the new `/erm/resource/{id}/entitlements` path
- Questions for @sosguthorpe:
- Do you know if **Acquisition method** should be `entitlement.resource.class === 'org.olf.kb.Pkg' ? 'Package' : 'Item'` [for/based on Scenario 2 here](https://issues.folio.org/browse/UIER-21).
- Some items returned from `/erm/resource/electronic` return a 404 when I look up their `/entitlements`. Should they be returning an empty array? E.g., the "American Psychological Association:Master" resource. Are they just anomalies of sample data?

E-resources: Update paths and list agreements

---

src/components/Agreements/AgreementForm/AgreementForm.js
src/components/Agreements/AgreementForm/Sections/AgreementFormEresources.js
src/components/Agreements/AgreementForm/Sections/AgreementFormInfo.js
src/components/Agreements/EditAgreement/EditAgreement.js
src/components/Basket/Basket.js
src/components/Basket/BasketList.js
src/components/Tabs/Tabs.js
src/routes/Agreements.js
translations/ui-erm/en.json

The Basket is now fully(?) in place and we can add resources to agreements from:
- the Edit Agreement page, where we select resources from the basket. (Added previously)
- the Basket, where we select resource and create new agreements based on them. (Added previously)
- the Basket, where we select resources and add them to existing agreements.
Had a decent amount of wrenching to do to get redux-form to do what I wanted (what else is new?) but that should be it.
Next up:
- handling all the busywork for the renamed repo.
- listing all individual titles, broken out of packages, covered by an agreement.

UIER-22 Basket: Added ability to add basket items to existing agreements

---

src/ERM.js
src/components/Tabs/Tabs.js

Previously, switching between the Agreements and E-resources tabs would keep the same filters/sort applied. This didn't really feel right to me so I've changed it to save off the current filters/sort whenever you're leaving to go to another tab, and then pull the persisted filters/sort off when you go _back_ to that tab.
Also turned on a default filter of non-closed agreements per UIER-4.

Tabs: Keep separate set of filters/sort for agreements and eresources

---

src/components/Agreements/AgreementForm/Sections/AgreementFormEresources.js
src/components/Agreements/ViewAgreement/Sections/AgreementInfo.js
src/components/Agreements/ViewAgreement/Sections/AssociatedAgreements.js
src/components/Agreements/ViewAgreement/Sections/Eresources.js
src/components/Agreements/ViewAgreement/Sections/EresourcesCovered.js
src/components/Agreements/ViewAgreement/Sections/License.js
src/components/Agreements/ViewAgreement/Sections/LicenseBusinessTerms.js
src/components/Agreements/ViewAgreement/Sections/Organizations.js
src/components/Agreements/ViewAgreement/Sections/VendorInfo.js
src/components/Agreements/ViewAgreement/ViewAgreement.js
src/components/BasketSelector/BasketSelector.js
src/components/BasketSelector/BasketSelectorDisplay.js
src/components/EResources/ViewEResource/Sections/AcquisitionOptions.js
src/components/EResources/ViewEResource/Sections/EResourceAgreements.js
src/components/EResources/ViewEResource/Sections/EResourceInfo.js
src/components/KBs/ViewKB/ViewKB.js
src/components/Titles/ViewTitle/ViewTitle.js
src/routes/Agreements.js
src/routes/EResources.js
src/routes/KBs.js
src/settings/index.js

https://github.com/folio-org/stripes-core/pull/489
Retrieving the `intl` object from `this.context.intl` or the `stripes` god object (`stripes.intl`) is a deprecated pattern.
Use `<FormattedMessage>`, `<FormattedDate>`, and `<FormattedTime>` as often as possible, only falling back to `formatMessage()`, `formatDate()`, and `formatTime()` (accompanied by `injectIntl()`) when a bare string is absolutely necessary.
`MultiColumnList` has some challenges receiving nodes in `columnMapping`, so I had to leave those `formatMessage()` uses alone for now: https://issues.folio.org/browse/STCOM-399

Replace formatMessage() with <FormattedMessage>

---

src/components/Agreements/ViewAgreement/ViewAgreement.js

- Fixed a string/node prop type mismatch when using `FormattedMessage`.
- Switched to the new `actionMenu` prop instead of deprecated `actionMenuItems`.

Switched to Pane's new actionMenu prop

---

src/components/Agreements/AgreementForm/AgreementForm.js
src/components/Agreements/AgreementForm/Sections/AgreementFormEresources.js
src/components/Agreements/AgreementForm/Sections/AgreementFormOrganizations.js
src/components/Agreements/AgreementForm/Sections/index.js
src/components/Agreements/EditAgreement/EditAgreement.js
src/components/Agreements/ViewAgreement/Sections/Organizations.js
src/components/Agreements/ViewAgreement/ViewAgreement.js
src/components/Basket/Basket.js
src/components/Basket/BasketList.js
src/components/CreateOrganizationModal/CreateOrganizationModal.js
src/components/CreateOrganizationModal/index.js
src/routes/Agreements.js
test/ui-testing/basket.js
translations/ui-agreements/en.json

- Allows the viewing and editing of organizations for a given agreement.
- Organizations can be added by selecting an existing organization and role from the dropdown menus.
- New organizations can be created using the Create New Organization button
- While working on this I switched to using the `Selection` component for the Basket instead of `AutoSuggest` since it improved the UX in terms of discoverability.

UIER-13 UIER-23: View/Edit Agreement Organizations

---

CHANGELOG.md
package.json

- Mainly to fix the issue of wrong version numbers being pushed to the folioci NPM registry
- Took the opportunity to bump to `@folio/stripes` 1.1

Release 1.1

---

src/components/Agreements/AgreementForm/AgreementForm.js
src/components/Agreements/AgreementForm/Sections/AgreementFormOrganizations.js
src/components/Agreements/ViewAgreement/ViewAgreement.js
src/components/OrganizationSelection/OrganizationSelection.js
src/components/OrganizationSelection/OrganizationSelectionContainer.js
src/components/OrganizationSelection/OrganizationSelectionDisplay.js
src/components/OrganizationSelection/index.js
src/routes/Agreements.js
translations/ui-agreements/en.json

**Problem**
Users can add organizations to an agreement. They do so by selecting which organization they want to add to the agreement from a `Selection`'s dropdown. The dropdown's option list was being populated by all the records at the `/erm/org` endpoint. However, that endpoint can return thousands of entries. We want to be able to search that endpoint based on the user's entered text so we can do filtering on the backend rather than locally.
**Solution**
- Create a component `OrganizationSelection` that renders it's descendants `OrganizationSelectionContainer` > `OrganizationSelectionDisplay`.
- `OS` merely `connect()`s `OSC` with a unique `dataKey` generated from the form field's name. This is so we can fetch different sets of orgs for each dropdown.
- `OSC` handles fetching of …

Organization Selection with an async options list

---

src/components/CoverageStatements/CoverageStatements.js

Multiple coverage statements for a single item were being rendered side-by-side rather than above one another. This fixes that.

CoverageStatements: Fixed rendering of multiple statements

---

src/components/Agreements/AgreementForm/Sections/AgreementFormEresources.js
src/components/Agreements/ViewAgreement/Sections/EresourceAgreementLines.js
src/components/Agreements/ViewAgreement/Sections/EresourcesCovered.js
src/components/Basket/BasketList.js
src/components/EResourceLink/EResourceLink.js
src/components/EResourceLink/index.js
src/components/EResources/EResourceAgreements/EResourceAgreements.js
src/components/EResources/ViewPackage/Sections/PackageResources.js
src/components/EResources/ViewTitle/Sections/AcquisitionOptions.js
src/components/FolioLink/FolioLink.js
src/components/FolioLink/index.js
src/routes/Agreements.js
src/routes/EResources.js

We render an eresource name as a link to its record fairly often. Moved this rendering into a component for more control and less duplication.

Added common EResourceLink component

---

package.json

This will allow Okapi to pull in the required backend module (mod-agreements) as part of the dependency resolution process. Requesting review, as I'm not sure if there was a reason this was omitted in the first place.
Towards UIER-30.

Add okapiInterfaces dependency to interface "erm" version 1.0.

---

src/components/Agreements/ViewAgreement/Sections/AgreementInfo.js
src/components/Agreements/ViewAgreement/Sections/Eresources.js
src/components/Agreements/ViewAgreement/Sections/EresourcesCovered.js
src/components/Agreements/ViewAgreement/Sections/InternalContacts.js
src/components/Agreements/ViewAgreement/Sections/Organizations.js

The agreement view pane has a bunch of accordions, some of which show lists of items such as internal contacts, covered eresources, etc. Now, those accordion's headers show the count of items in that accordion.

Show item counts in accordion header

---

test/ui-testing/basket.js

Updated to use the new classnames introduced in folio-org/stripes-components#849

ERM-5: Fixed tests to handle new MCL classnames

---

CHANGELOG.md
package.json
src/components/Agreements/AgreementForm/Sections/AgreementFormExternalLicenses.js
src/components/Agreements/AgreementForm/Sections/AgreementFormInfo.js
src/components/Agreements/AgreementForm/Sections/AgreementFormLicense.js
src/components/Agreements/ViewAgreement/Sections/AgreementInfo.js
src/components/Agreements/ViewAgreement/Sections/ExternalLicenses.js
src/components/Agreements/ViewAgreement/Sections/License.js
test/ui-testing/external-licenses.js
translations/ui-agreements/en.json

* ERM-41: Added ability to CRUD external licenses for agreements.
* ERM-42: Add external licenses to agreements
* ERM-43: Edit external licenses for agreements
* ERM-44: Remove external licenses from agreements
Lots of code reuse due to generalising `DocumentCard` and `DocumentsFieldArray` into `stripes-erm-components`

ERM-41 ERM-42 ERM-43 ERM-44: CRUD External Licenses for Agreements

---

src/components/Agreements/ViewAgreement/ViewAgreement.js

We should come up with a longer-term solution than this but as-is `ui-agreements` is broken if run on a platform without whatever module implements the `orders-storage` endpoint.

ERM-30: Don't throw errors from orders-storage endpoint

---

package.json
test/ui-testing/agreement-crud.js
test/ui-testing/linked-licenses.js

- Augmented the `linked-licenses` test to check that the linkage is visible in the Licenses module.
- Removed the `linked-licenses` test from the default run because it requires the Licenses module as well as the Agreements module. It'll be added as an integration test of `platform-erm`.
- Updated our dependency on lodash due to security errors.

ERM-63: Tests

---

src/components/Agreements/ViewAgreement/Sections/Finances.js
src/components/Agreements/ViewAgreement/ViewAgreement.js
translations/ui-agreements/en.json

If there exists an invoice line where one of the poLineIds matches one of the poLineIds of the
current agreement then display the "Show invoices" link.
Endpoint to query: /invoice-storage/invoice-lines
https://github.com/folio-org/mod-invoice-storage/blob/master/ramls/invoice.raml
https://github.com/folio-org/acq-models/blob/master/mod-invoice-storage/schemas/invoice_line.json
The link label is shown but without a clickable link because the destination doesn't exist yet:
https://github.com/folio-org/ui-invoice

UIER-34: Display "show invoices" link

---

package.json
src/components/Agreements/AgreementForm/components/AgreementLineField.js
src/components/Agreements/AgreementForm/components/AgreementLinesFieldArray.js
src/components/Agreements/AgreementForm/components/CustomCoverageFieldArray.js
src/components/Agreements/AgreementForm/components/EditCard.css
src/components/Agreements/AgreementForm/components/EditCard.js
src/components/Agreements/AgreementForm/components/withKiwtFieldArray.js
src/components/Agreements/ViewAgreement/Sections/EresourceAgreementLines.js
src/components/Agreements/ViewAgreement/Sections/EresourcesCovered.js
src/components/Agreements/ViewAgreement/ViewAgreement.js
src/components/CoverageStatements/CoverageStatements.js
src/components/CustomCoverageIcon/CustomCoverageIcon.js
src/components/CustomCoverageIcon/index.js
src/components/EResources/EResourceAgreements/EResourceAgreements.js
src/components/withKiwtFieldArray.js
test/ui-testing/agreement-crud.js
test/ui-testing/basket.js
test/ui-testing/custom-coverage.js
test/ui-testing/nav.js
test/ui-testing/utils.js
translations/ui-agreements/en.json

Feature
- Set custom coverage for agreement lines
- Not available for agreement lines for packages
- View coverages on the agreement-lines, eresources-covered, and agreement-lines-for-eresource tables
- View custom coverage indicators (`<CustomCoverageIcon>` on aforementioned tables
- Icon will be changed after Q1 code freeze. Need to get icon into stripes-components and don't want to depend on a version of stripes-components that won't be in Q1.
- Tests
Reusables
- Added `withKiwtFieldArray` HOC to handle all the nuances of the arrays used by the backend.
- Added `<EditCard>` component for field array items.

ERM-65/ERM-104/ERM-105/ERM-106/ERM-107: Custom Coverage for Titles

---

src/components/Agreements/AgreementForm/Sections/AgreementFormInfo.js
src/components/Agreements/AgreementForm/Sections/AgreementFormOrganizations.js
src/components/Agreements/ViewAgreement/Sections/AllLicenses.js
src/components/Agreements/ViewAgreement/Sections/Eresources.js
src/components/Agreements/ViewAgreement/Sections/Finances.js
src/components/Agreements/ViewAgreement/Sections/FinancesAgreementLines.js
src/components/Agreements/ViewAgreement/Sections/LicenseInfo.js
src/components/Agreements/ViewAgreement/Sections/Organizations.js

We have accordions inside of accordions in several places on the View and Edit Agreement pages. These accordions should be uniformly indented to show their relationship to the parent.

Cleaned up indents of agreement subaccordions

---

src/components/Agreements/AgreementForm/components/CustomCoverageFieldArray.js
translations/ui-agreements/en.json

Added a new `validate` check to ensure multiple open-ended custom coverages cannot be set for a single agreement line.

ERM-128: Prevent multiple open-ended custom coverages from being saved

---

src/components/Agreements/AgreementForm/components/CustomCoverageFieldArray.js

Coverages that were previously saved but now deleted were being interpreted as open-ended coverages because of the non-existence of an `endDate` on their `coverage` object.

ERM-128: Additional fix for multiple open-ended coverages

---

src/components/Agreements/AgreementForm/components/CustomCoverageFieldArray.js

When deleting an agreement line, the validators fire one last time before the item is gone for good (and the validators fire again). In that scenario, the `get` for the `coverage` array can fail because the `items[x]` doesn't exist.
Added a default empty coverage array so that the validators return no error in that run.

Coverage: Prevent undefined array dereference

---

src/components/Agreements/ViewAgreement/Sections/EresourceAgreementLines.js
src/components/Agreements/ViewAgreement/Sections/EresourcesCovered.js
src/components/CustomCoverageIcon/CustomCoverageIcon.js
translations/ui-agreements/en.json

- Can't put it in stripes-components' `<Icon>` component because it'd have to be monochrome.
- Can't have it as an `<AppIcon>` because of the border-radius.
- Had to inline it.

ERM-131: Use custom custom coverage (heh) icon

---

package.json
src/ERM.js
src/components/Agreements/AgreementForm/components/AgreementLineField.js
src/components/Agreements/AgreementForm/components/AgreementLinesFieldArray.js
src/components/Agreements/EditAgreement/EditAgreement.js
src/components/Agreements/ViewAgreement/Sections/EresourceAgreementLines.js
src/components/Agreements/ViewAgreement/ViewAgreement.js
src/components/Basket/BasketList.js
src/components/EResourceLink/EResourceLink.js
src/components/EResources/EResourceAgreements/EResourceAgreements.js
src/components/FolioLink/FolioLink.js
src/components/ResourceCount/ResourceCount.js
src/components/ResourceCount/index.js
src/components/ResourceProvider/ResourceProvider.js
src/components/ResourceProvider/index.js
src/components/ResourceType/ResourceType.js
src/routes/Agreements.js
src/util/getResourceFromEntitlement.js
src/util/isExternal.js
test/ui-testing/basket.js
test/ui-testing/ekb-int.js
translations/ui-agreements/en.json

- Pull `authority` and `referenceId` from query string when creating agreement and use it to lookup package/resource info from `/erm/entitlements/external`.
- Lots of generalising and componentising to support different sources of data for external/internal eresources.
- `test-ekb-int` to run integration tests for the above features. Naturally, this requires eHoldings to be installed and configured with EBSCO keys.

ERM-109/110 eHoldings Integration

---

src/components/Agreements/ViewAgreement/Sections/EresourceAgreementLines.js

Wasn't necessary to define one before as we were rendering the text/number directly. Now we're rendering a component and MCL has wide default column widths for formatters that return components.

Shrink size of count column

---

package.json
test/ui-testing/license-terms.js
test/ui-testing/linked-licenses.js

Some identifiers changed in https://github.com/folio-org/ui-licenses/pull/144 so this updates the selectors for any integration tests between Licenses and Agreements.

Updated tests for Licenses refactor

---

package.json
src/components/Tabs/Tabs.js
src/routes/Dashboard.js
translations/ui-agreements/en.json
translations/ui-agreements/en_US.json

Handled the display-side renaming of "ERM" to "Agreements".
This does not change any URLs and the underlying module is already called `ui-agreements` so we're fine on that front.
This also fixes a bug that happened when you clicked on a particular part of the tab list nav buttons that would result in navigating to a blank page.

ERM-197 Rename ERM to Agreements

---

src/components/Agreements/ViewAgreement/ViewAgreement.js

Notes attempts to fetch based on the `entityId`, and the failed `GET` call can crash the page from inside stripes-connect.

Notes: Always provide an entityId

---

src/components/Agreements/ViewAgreement/Sections/InternalContacts.js
src/components/Agreements/ViewAgreement/ViewAgreement.js

Top-level accordions need to respond to their parent's bulk toggles.

Contacts: Fixed accordion not responding to toggle

---

src/components/AgreementSections/Header.js
src/components/AgreementSections/Info.js
src/components/AgreementSections/LinkedLicenses.js
src/components/CoverageStatements/CoverageStatements.js
src/components/EResourceSections/Agreements.js
src/components/FormattedUTCDate/FormattedUTCDate.js
src/components/FormattedUTCDate/index.js
src/components/views/Agreements.js
src/components/views/Basket.js

mod-agreements is only responding with date strings as of https://github.com/folio-org/mod-agreements/pull/144 and https://github.com/folio-org/mod-agreements/pull/145
This means that when we pump a date like `2019-07-01` into react-intl's `FormattedDate`, it interprets that as `2019-07-01T00:00:00Z`. As part of the formatting, it translates it according to the tenant's time zone. As a result, any `-`-offset timezone from UTC will actually render that date as something like `6/30/2019` and not `7/1/2019`. This is a problem.
To get around this, we can pass `timeZone="UTC"`, [one of the DateTimeFormatOptions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Parameters), into `FormattedDate`.
And rather than passing in that prop every single …

ERM-276: Support date strings instead of datetime strings

---

test/ui-testing/agreement-crud.js

Attribute selectors need to have their values quoted.

Quote id of resourceId when searching for it

---

src/components/LicensesFieldArray/LicenseLookup.js
test/ui-testing/license-terms.js

Without setting a unique `dataKey`, the plugin reuses the resources for previous uses of it. This ensures it uses the default filters/queries each load.

ERM-288: Set dataKey for find-license plugin

---

src/routes/AgreementEditRoute.js
src/routes/AgreementViewRoute.js

Fetching PO Lines no longer occurs because a new Orders interface version of 7.0 is out. The `okapiInterfaces` has been updated but the `fetch` conditionals need to be as well.

ERM-374: Support Orders interface 7.0

---

src/components/UsageDataProvidersFieldArray/UsageDataProviderField.js

There's another `renderEmpty` below this one - that's the one we're using.

Remove unused method

---

CHANGELOG.md
src/components/AgreementLinesFieldArray/POLineField.js
src/components/AgreementSections/InternalContacts.js

Using the new `InternalCardComponent` introduced in https://github.com/folio-org/stripes-erm-components/pull/102

ERM-309: Render internal contacts as cards

---

CHANGELOG.md
package.json
src/routes/AgreementViewRoute.js

Now listing `organizations-storage.interfaces` in `okapiInterfaces` so that a major version can't be pushed to a platform without us knowing.

Added support for mod-orgs-storage 2.0

---

test/ui-testing/docs.js
test/ui-testing/orgs.js

- Orgs changed their default filter values
- Stopped checking the 'Active' checkbox
- Accordion rendering got tweaked somehow so that the document elements were present but were not being filled with data.
- Expanded all accordions before `evaluate`ing

Fixed tests

---

CHANGELOG.md
package.json
src/routes/EResourceViewRoute.js

- We could write these MCLs with `virtualize` and
`onNeedMoreData` props but I think it might be
too heavy-handed and also hurts the scrollability
and discoverability of the list.
- We can revisit this if this proves a horrible idea.

ERM-409: Fixed truncated package contents

---

src/routes/EResourceViewRoute.js

Was missing a couple of these params. _Hopefully_, we'll literally never use this functionality because it means a library has _over a hundred agreements_ for a single eresource which would be....weird...but I guess theoretically possible once you factor in trial/expired/cancelled agreements...?

EResource Agreements: support paging

---

src/components/AgreementLinesFieldArray/CustomCoverageFieldArray.js
src/components/AgreementPeriodsFieldArray/AgreementPeriodsFieldArray.js
src/components/utilities/validators.js
translations/ui-agreements/en.json
translations/ui-agreements/en_US.json

Generalising the validators also resulted in reusing the same error messages...whoops! This keeps the logic general but allows the message to be specified external to the method.

ERM-501: Fixed error messages for date fields

---

src/components/views/EResources.js
src/routes/AgreementsRoute.js
src/routes/EResourcesRoute.js

- Sort tags via the CQL.
- Realised we don't use tags in eresources so pulled that query out.

ERM-522: alphasort tags in SAS filter

---

src/components/BasketList/BasketList.js

This would've broken during the MCL refactor because the isChecked state is stored external to the props (in `contentData`) and thus doesn't trigger a rerender of the PureComponent. To get around this, we need to set the `rowUpdater` prop.

ERM-525 BasketList: Fixed checkbox not rerendering

---

src/components/LicensesFieldArray/LicenseField.js
src/components/RelatedAgreementsFieldArray/RelatedAgreementField.js

If a repeating field's `Field` component mounts without a value, it means that it was just added via the corresponding `Add new {resource}` button. In that case, we should automatically focus the field's `Add {resource}` button which brings up the `find-{resource}` modal for linking the resource to the agreement being edited.

Autofocus "Add (resource)" button on creation

---

src/components/views/AgreementForm.js
src/routes/AgreementCreateRoute.js
src/routes/AgreementEditRoute.js

- The `if` conditions in `gDSFP` were too strict. Relaxed those to also catch scenarios where the agreement fetched has changed (via its id).
- I also fixed a bug where the `addFromBasket` query params weren't being reset properly due to vagaries in the stripes-core reducer. The order of `update()` calls is correct, but at one point `<Root>` takes the location URL as the source of truth rather than the existing state which seems...off...
- Will debug stripes a bit more but this way of doing things is cleaner and more direct anyway.

ERM-534: Fixed using stale agreement data on edit route

---

src/components/AgreementLinesFieldArray/AgreementLineField.js
src/components/AgreementLinesFieldArray/CustomCoverageFieldArray.js
src/components/AgreementPeriodsFieldArray/AgreementPeriodsFieldArray.js
src/components/AgreementSections/FormInfo.js
src/components/AgreementSections/FormLicenses.js
src/components/LicensesFieldArray/AmendmentsFieldArray.js
src/components/LicensesFieldArray/LicensesFieldArray.js
src/components/RelatedAgreementsFieldArray/RelatedAgreementsFieldArray.js
src/components/UsageDataProvidersFieldArray/UsageDataProvidersFieldArray.js
src/routes/AgreementEditRoute.js

[ERM-564](https://issues.folio.org/browse/ERM-564)
Backends written in Groovy do not interpret an undefined value as being an "unsetting" of a field. Eg, if a given record has `{ id: 1, foo: "bar", bar: "baz" }` and I PUT `{ id: 1, foo: "aubergine" }`, then the record will now have `{ id: 1, foo: "aubergine", bar: "baz" }`.
This is a problem for us because [React Final Form coalesces empty strings into undefineds](https://final-form.org/docs/final-form/faq#why-does-final-form-set-my--field-value-to-undefined). To work around this, we use [the docs' suggested `parse` hack](https://final-form.org/docs/react-final-form/types/FieldProps#parse).

ERM-564: Support unsetting of optional fields

---

src/routes/AgreementViewRoute.js
test/bigtest/tests/duplicate-agreement-modal-test.js

- The catch block fails with _cannot read catch of undefined_  [here](https://github.com/folio-org/ui-agreements/blob/master/src/components/DuplicateAgreementModal/DuplicateAgreementModal.js#L104) in the tests. To account for this we need to return a resolved promise such as `onClone = spy(() => Promise.resolve())`  in the test  so that the assumption `props.clone()`  (returns a Promise) makes is actually true, which also means moving away from the async await logic in place. This PR covers that.
- Fix test failures

return a resolved promise onClone

---

src/components/views/AgreementForm.js

- Something changed in final-form 4.18.6 so iV isn't being
updated properly. Switched to use `values` instead until
the bug is fixed.
- https://github.com/final-form/final-form/issues/300

Don't rely on props.initialValues

---

src/components/views/AgreementForm.js

- `props.initialValues` started being stale in FF 4.18.6, this is a workaround
- https://github.com/final-form/final-form/issues/300

Don't rely on props.initialValues for agreement lines

---

src/components/AgreementSections/LinesList.js
src/routes/AgreementEditRoute.js

External Entitlements don't render the activeTo/From fields so use the more generic start/endDate fields which pull from the same datasource.

Lines: Use start/endDate instead of activeFrom/To

---

src/components/AgreementLinesFieldArray/AgreementLineField.js
src/components/AgreementLinesFieldArray/AgreementLinesFieldArray.js

The current code always pulled the activeTo/From values and assumed they were valid, which is incorrect. 
For example, if `activeTo` wasn't set in the form, then `activeTo = new Date(get(allValues, meta.name.replace('activeFrom', 'activeTo')));` results in setting the `activeTo` variable to the start of the UNIX epoch, Dec 31 1969. 
This then results in any `activeFrom` value greater than 1970 failing validation.

Fixed agreement line activeTo/From validation

---

CHANGELOG.md
package.json
src/components/AgreementSections/CoveredEResourcesList.js
src/components/AgreementSections/Header.js
src/components/AgreementSections/Info.js
src/components/AgreementSections/Lines.js
src/components/AgreementSections/LinesList.js
src/components/AgreementSections/OtherPeriods.js
src/components/CoverageStatements/CoverageStatements.js
src/components/EResourceSections/AcquisitionOptions.js
src/components/EResourceSections/Agreements.js
src/components/EResourceSections/PackageContents.js
src/components/FormattedUTCDate/FormattedUTCDate.js
src/components/FormattedUTCDate/index.js
src/components/LicenseAmendmentList/LicenseAmendmentList.js
src/components/LicensesFieldArray/AmendmentsFieldArray.js
src/components/views/Agreements.js
src/components/views/Basket.js

Spinner and FormattedUTCDate were promoted to Stripes as of version 2.12.0 so we should switch to pulling them from there from now on.

ERM-636: Use Spinner and FormattedUTCDate from Stripes

---

src/components/AgreementSections/CoveredEResourcesList.js
src/routes/AgreementEditRoute.js
src/routes/AgreementViewRoute.js
test/ui-testing/agreement-crud.js
translations/ui-agreements/en.json

- Added Callout for when exporting resources. 
- While testing the Dropdown changes, I realised that exporting a resources list that's really long is super confusing because you get no notification. So I added a Callout.
- Additionally, this Callout uses the functionality I added in https://github.com/folio-org/stripes-components/pull/1130 to autohide when the download is done.
- Fixed Custom Coverage test by having the agreement creation helper not add expired agreement lines
- The custom coverage test was looking for an entry in the eresources covered list, but the eresources wasn't there because the default filter is 'Current', and the line was added with an expired access date.

Support updated Dropdown API

---

src/routes/AgreementEditRoute.js
src/routes/AgreementViewRoute.js

The last PR handled _viewing_ the agreement lines, but it missed loading them up when editing the agreement.

ERM-654: Disable ag line sort

---

package.json
src/components/AgreementLinesFieldArray/POLineField.js
src/components/AgreementSections/LinesList.js
test/bigtest/helpers/findPOLineModule.js
test/bigtest/tests/po-lines-test.js

- Depend on new `order-lines` `1.0` interface
- Use `poLine.titleOrPackage` instead of `title`

ERM-652: Support orders 9.0 interface

---

package.json
src/routes/AgreementViewRoute.js

The `okapiInterfaces` was updated previously but not the `hasInterface` check so the order-lines fetches were never happening.

AgViewRoute: Update hasInterface check

---

src/components/EResourceSections/PackageContents.js
src/components/views/EResources.js

Renders a load more button which on click will render the next N results (currently 100). Opting in for this behavior until the scroll functionality is well supported. Opting in to scroll should be as easy as changing the `pagingType` prop to `scroll`

Use pagingType click, refs ERM-642

---

src/components/AgreementSections/FormInternalContacts.js
src/components/Coverage/MonographCoverage.js
src/components/Coverage/SerialCoverage.js

[This will hopefully alleviate some MCL column sizing issues as described in this thread.](https://folio-project.slack.com/archives/CAYCU07SN/p1583856407069400)
Also put in a fix for a bug I saw where the wrong translation ID was being used for internal contacts.

Render null coverage as null instead of hyphen

---

CHANGELOG.md
package.json
src/components/Coverage/MonographCoverage.js
src/components/DuplicateAgreementModal/DuplicateAgreementModal.js
src/components/views/Agreement.js
src/components/views/Agreements.js
src/routes/AgreementViewRoute.js
translations/ui-agreements/en.json

- Makes the `Agreements: Delete agreements` permission set visible and assignable.
- Adds `Delete` dropdown button
- Front-end checks for whether the agreement has lines, linked licenses, or related agreements. Disallows deletion if it does.
- Scoped `shouldRefresh` so that we don't attempt to try to fetch an `agreement` resource that was just deleted. Uses functionality added in https://github.com/folio-org/stripes-connect/pull/133

ERM-777: Allow deleting of agreements

---

src/components/AgreementSections/FormSupplementaryDocuments.js
src/routes/AgreementCreateRoute.js
src/routes/AgreementEditRoute.js

- Fetches documentCategories from the `erm/refdata/DocumentAttachment/atType` endpoint
- Also cleaned up the lodash `get`s in `AgreementEditRoute`

Add categories to Agreements supplementary documents, refs ERM-746

---

src/components/AgreementLineSections/Coverage.js
src/routes/AgreementLineEditRoute.js

ERM-921
- Switched to using `FormattedUTCDate` and fixed a c/p error.
ERM-922
- Only passed `coverage` along as part of `initialValues` if the `customCoverage` flag was set.
- We already use this approach when editing the agreement itself.

ERM-921 ERM-922: AgLine coverage bug fixes

---

src/components/views/AgreementLine.js
src/routes/AgreementLineViewRoute.js
translations/ui-agreements/en.json

Needed to add some `throwErrors: false`. We don't want to turn off resource-refreshing because the deletion occurs via a PUT.

ERM-924: Added confirmation when deleting agline

---

src/components/AgreementLineSections/Coverage.js
src/components/AgreementLineSections/FormCoverage.js
translations/ui-agreements/en.json

- Show Embargo details when viewing/editing an agreement line
- AgLine View: Show `Default` for coverage type in default coverage rows.

ERM-938 ERM-939: Show Embargo info on AgLine pages

---

src/components/TitleCard/TitleCardInfo.js

React complains on the console when a key is not set for array elements because it's required to set one.

Set keys for RelatedTitleInfo

---

src/components/Coverage/MonographCoverage.js
translations/ui-agreements/en.json
translations/ui-agreements/en_US.json

* return null instead of * for monograph w/o coverage in MonographCoverage
* fix typo for 'relatedAgreements.relationship.has_frontfile_in' in en.json and en_US.json

refs ERM-1120 ERM-1130

---

src/components/views/Agreement.js

Added a keyboard shortcut  (`alt + c`) to which can be used to duplicate a record if document focus is within a record's view. (anywhere in the detail pane.)

STCOM-770 Add duplicateRecord handler

---

src/components/AgreementSections/Header.css

https://github.com/folio-org/stripes-components/blob/master/lib/Accordion/Accordion.js#L143 has z-index set to 2. We need our  headers z-index to be bumped to 3 to solve the issue

Bump z-index to 3, refs ERM-1464

---

CHANGELOG.md
src/components/NoPermissions/NoPermissions.test.js
src/components/views/Agreement.js
src/components/views/AgreementForm.js
src/components/views/AgreementLine.js
src/components/views/AgreementLineForm.js
src/components/views/Agreements.js
src/components/views/PCI.js
src/components/views/PCIForm.js
src/components/views/Package.js
src/components/views/Platform.js
src/components/views/PlatformForm.js
src/components/views/Title.js
src/components/views/TitleForm.js
src/components/views/UrlCustomizer.js
src/components/views/UrlCustomizerForm.js
src/index.js
src/routes/AgreementCreateRoute.js
src/routes/AgreementEditRoute.js
src/routes/AgreementLineCreateRoute.js
src/routes/AgreementLineEditRoute.js
src/routes/AgreementLineViewRoute.js
src/routes/AgreementViewRoute.js
src/routes/AgreementsRoute.js
src/routes/EResourceEditRoute.js
src/routes/EResourceViewRoute.js
src/routes/UrlCustomizerCreateRoute.js
src/routes/UrlCustomizerViewRoute.js

- use handleSaveKeyCommand function from stripes-erm-components
- import keyboard functions from stripes-components
- add expand and collapse accordion shortcuts to Platform view
- fix lint error in NoPermissions.test.js

keyboard shortcut cleanup

---

package.json

Correct visible platforms permission displayNames to indicate they are part of Agreements

ERM-1592: Update displayName for ui-agreements.platforms.X permissions

---

src/components/views/Agreement.js

Unlike plugins, for which the "best" plugin of the requested type is selected, _all_ handlers of the relevant type are included. This approach uses the `<HandlerManager>` facility provided by stripes-core.

Add a surface for Stripes handler modules to present extensions

---

src/components/views/Agreement.js

The `ui-agreements-extension`-typed plugin ui-plugin-eusage-reports needs to know details of the agreement, which are contained in the `data` object along with other potentially useful information.

Pass data into handler

---

package.json

this commit is just to bump up interface version to fix testing env and deploy recent changes on snapshot.
in scope of order-lines v3.0 `acquisitionMethod` type was changed from hardcoded strings to uuid (dynamic values), so 
ui-agreements app won't be broken with this change, but acquisitionMethod field will display UID instead of readable string
after acquisitionMethod is fixed in this module, module major version should be updated, additionally order-lines v2.0 should be removed from interface dependencies

Bump up order-lines interface version (hosted env build fix). Refs ERM-1937.

---

src/routes/AgreementViewRoute/AgreementViewRoute.js

Infinite loop was being caused by unsafe integer addition. Reminder to myself and anyone else that might be caught out that:
2 + true === 3
2 + false === 2
2 + null === 2
2 + undefined === NaN
Nan === NaN is false
Defaulted any undefined lengths to 0 to avoid this issue.
ERM-1999

fix: Javascript equivalence problem

---

src/routes/AgreementViewRoute/AgreementViewRoute.js

Ensure initial fetch for users, so that subsequent agreement fetch will then refresh that call (stripes-connect not returning original params would somehow mean that an agrement refresh down the road would not then fetch that resource. This fixes that)
This work includes a tweak to how the `fetch` param is calculated, to avoid an unnecessary initial call to users before the agreement has loaded. This way the resource exists in stripes-connect ready for refreshing, but the call itself is not made.
refs ERM-2063

fix: Agreement Internal Contact fetch

---

src/routes/EResourceViewRoute/EResourceViewRoute.js

Settings for page sizes in eresource view were incorrect, because an incorrect prop shape was being passed to the parsing function.
ERM-2208

fix: ParseMclPageSize

---

src/components/AgreementSections/CoveredEResourcesList/CoveredEResourcesList.js

Added an initial check for `issn` ahead of `eissn` and `pissn`, since all new identifiers on TIs will be flattened to `issn`
ERM-2206

fix: ISSN not displaying in "E-resources covered by this agreement" list, refs ERM-2206

---

src/settings/components/AgreementsCustomProperties/AgreementsCustomProperties.js
translations/ui-agreements/en.json

Added translation labelOverride to CustomPropertiesSettings so that we surface deletion failures to the users again, and with a message specific to agreements.
ERM-2204

fix: delete failure callout

---

src/components/AgreementFilters/AgreementFilters.js

Previously we were using the length of the refdata list to know when to redraw. Swapping that out for a lodash `isEqual` allows for a more complicated check, including embedded labels.
ERM-2205

fix: Filters now update after refdata label changes

---

src/components/AgreementFilters/AgreementFilters.js

Filtering by tags did not previously work. We were overwriting the important Tag value manipulation via an automated "value" handler which was not meant to include tags
ERM-2223

fix: Agreement Tag filter

---

src/routes/AgreementCreateRoute/AgreementCreateRoute.js
src/routes/AgreementEditRoute/AgreementEditRoute.js
src/routes/AgreementLineCreateRoute/AgreementLineCreateRoute.js
src/routes/AgreementLineEditRoute/AgreementLineEditRoute.js
src/routes/AgreementViewRoute/AgreementViewRoute.js

Changed query namespacing convention for fetching an agreement to that outlined in ERM-2227.
Also invalidate license linkedAgreement calls when an agreement with linked licenses is edited or created.
ERM-2225, ERM-2227

fix: Query Namespacing

---

src/routes/AgreementCreateRoute/AgreementCreateRoute.js
src/routes/AgreementEditRoute/AgreementEditRoute.js

Previously agreements without linked licenses would fail to complete after-query calls to invalidate licenses, thanks to a missing null safety, which is now in place
ERM-2229

fix: Agreement creation/edit null safety

---

package.json

Bumped kint-components dependency to 2.8.2 to ensure we get the EBSCO-safe error handling in settings
ERM-2282

build: Kint-Components dep

---

src/components/views/Agreement/Agreement.js
src/components/views/AgreementLine/AgreementLine.js
src/routes/AgreementLineViewRoute/AgreementLineViewRoute.js
src/routes/AgreementViewRoute/AgreementViewRoute.js
src/routes/EResourceViewRoute/EResourceViewRoute.js

Currently the Tags component relies on the invalidation for the resource being the same as its fetch endpoint, added comments to this effect, and invalidateLinks to the Tags component where necessary
ERM-2297

chore: Tags invalidation comment

---

package.json
src/components/LicensesFieldArray/LicensesFieldArray.js

We previously had `onClick={onAddField}` instead of `onClick={() => onAddField()}`. The first one is a javascript shortcut for: `onClick={(e) => onAddField(e)}`, and for this function if you pass a prop in it will use that as the starting point for the field, so it was attempting to add a click event to the field, instead of an empty linked license object.
Also made babel core dep ^ instead of static
ERM-2299

fix: useKiwtFieldArray onAddField used incorrectly

---

src/components/AgreementLineFilters/AgreementLineFilters.js

For historical reasons, having no filterKey configured in the generateKiwtQueryParams means that the resulting filter array (such as [type==detached, type isNull] will be sent to the backend as separate filters.
As far as I can tell, we only use this in the custom property filter builder, but it represents a breaking change to a key piece of functionality, so instead of setting up a dodgy hack fix in the generateKiwtQueryParams function itself, or breaking the functionality altogether, this fix wrangles the edge case
Essentially we ensure that ONLY a single filter is EVER sent to generateKiwtQueryParams, similar to what we do with start/end date filters in Agreements
ERM-2338

ERM-2338: Selecting "Agreement line type" boxes in filter should use OR (||) not AND

---

src/components/views/AgreementLineForm/AgreementLineForm.js
src/routes/AgreementLineCreateRoute/AgreementLineCreateRoute.js

Fixed redirect behaviour upon "create another" from the agreement line create screen.
(Briefly redirect to view in order to force rerender of form without losing any other local state eg Basket)
ERM-2356

fix: Redirect

---

src/routes/AgreementsRoute/AgreementsRoute.js

fix: ERM-2382: Unchecking all search field boxes in Agreements carries out search with no fields
QIndex was being adhered to even when it was an empty string: ''. This work adds an explicit check for that case:
`searchKey: qIndex ?? defaultQIndex,` =>
`searchKey: (!!qIndex && qIndex !== '') ? qIndex : defaultQIndex,`
ERM-2382

ERM-2382: Unchecking all search field boxes in Agreements carries out search with no fields

---

src/components/views/Agreements/Agreements.js

Moved AgreementFilters outside of the <form> rendered for the Search field. This stops the issue where CustomPropertiesFilters was throwing a console error due to a nested <form> component
ERM-2397

fix: AgreementFilters

---

src/components/views/Packages/Packages.js
src/components/views/Platforms/Platforms.js
src/components/views/Titles/Titles.js

Changed pane ids to allow responsive button group to work more seamlessly accross the local kb search tabs

style: Responsive panes

---

src/components/IdentifierReassignmentForm/DestinationTitleIdentifierField/DestinationTitleIdentifierField.js
src/components/IdentifierReassignmentForm/SourceTitleIdentifierField/SourceTitleIdentifierField.js

Fixed an issue in which selecting a title for either source or destination title within the move identifiers modal would not have that title be set within the card
[ERM-2917](https://issues.folio.org/browse/ERM-2917)

ERM-2917: Fix move identifiers e-resource plugin

---

src/components/views/AgreementForm/AgreementForm.js
src/routes/AgreementEditRoute/AgreementEditRoute.js
src/routes/AgreementEditRoute/AgreementEditRoute.test.js

Removed additional fetches for agreement lines and entitlements, redundant tests from AgreementEditRoute and props which are no longer used from the AgreementForm view
[ERM-2421](https://issues.folio.org/browse/ERM-2421)

ERM-2421: Agreement lines and entitlements additional fetches

---

src/hooks/useChunkedOrderLines.js

chore: useChunkedOrderLines
Swap useChunkedOrderLines to improved useChunkedCQLFetch implementation
refs ERM-2967

ERM-2967: Use useChunkedCQLFetch consistently across ERM

---

src/constants/httpStatuses.js
src/constants/index.js
src/routes/AgreementEditRoute/AgreementEditRoute.js
src/routes/AgreementViewRoute/AgreementViewRoute.js
src/routes/BasketRoute/BasketRoute.js
src/routes/EResourceViewRoute/EResourceViewRoute.js

feat: Swap to parallel fetch hooks
Swapped over to use useParallelBatchFetch and useChunkedUsers instead of useBatchedFetch and useUsers
refs ERM-2973, ERM-2976, ERM-2977

ERM-2973: Replace naive fetch hooks with parallelised ones (and deprecate)

---

package.json

build: @rehooks/local-storage
Removed lock on @rehooks/local-storage
ERM-3036

ERM-3036: unlock @rehooks/local-storage from 2.4.4

---

src/components/AgreementDocumentFilter/AgreementDocumentFilterRule.js

Fixed issue in which rule field array would display or instead of and for rules within an idividual filter
[ERM-3052](https://issues.folio.org/browse/ERM-3052)

ERM-3052: In Document filter builder OR displays on screen instead of AND

---

src/components/AgreementContentFilter/AgreementContentFilter.js
src/constants/agreementContentOptions.js

Added related agreements option for the agreement content filter, also added special handling for seperating the related agreement option so that both inward and outward relationships can be queried within the agreement
[ERM-3052](https://issues.folio.org/browse/ERM-3054)

ERM-3052: Related agreements option missing from Agreement content filter

---

src/components/AgreementDocumentFilter/AgreementDocumentFilter.js
src/components/AgreementDocumentFilter/AgreementDocumentFilterRule.js

Replaced "Type" translation with "Category" within attributes data options array
[ERM-3060](https://issues.folio.org/browse/ERM-3060)

ERM-3060: Use "Category" not "Type" in document filter

---

src/routes/AgreementLinesRoute/AgreementLinesRoute.js

fix: Change in enabled logic for agreement lines
While changing AgreementLines to paginated, logic was removed: https://github.com/folio-org/ui-agreements/pull/1257/files#diff-a4104c109644976b86e2b1f79d0df43a92845844a16ff4344e460982f4a71cd9L74 and was subsequently not caught by CodeReview
This PR adds that back in
ERM-3065

ERM-3065: Agreement lines are displayed by default on the "Agreement lines" pane.

---

src/components/AgreementContentFilter/AgreementContentFilter.js
src/components/AgreementDocumentFilter/AgreementDocumentFilter.js

Removed replaceAll functions from documents and content filters deparseKiwtQueryFilters due to changes made to web-toolkit
ERM-3061

fix: Filter deparse regex

---

src/components/AgreementContentFilter/AgreementContentFilter.js

fix: Comparator spacing
Fixes made in kint-components means we can no longer bank on lack of spacing for "special" comparators. These _need_ a space as a part of the comparator, and this change reflects that.
ERM-3081

ERM-3081: Do not add a space after search operator when doing groupings

---

src/components/AgreementSections/Header/Header.css

* fix same issue in ui-agreements
* adjust .agreementHeader class
* fix also text shadow above sticky header

ERM-3182 Scrolling content in license view pane can overlap header

---

src/constants/endpoints.js

Made a tiny tweak to swap the default entitlementOptions fetch out to the newer static endpoint. We don't currently sort or filter on this, so we can do this with no other changes required
refs ERM-3246

chore: Swap to /static/entitlementOptions

---

src/routes/EResourceViewRoute/EResourceViewRoute.js

On snapshot we see extra calls to entitlementOptions where `page=undefined`. This does _not_ happen locally for me, which is confusing, but regardless I've added an enabled check to hopefully stop this behaviour
refs ERM-3246 (But is not required for that functionality to work)

fix: Extra calls

---

CHANGELOG.md
package.json

Updated changelog and bumped version to 11.0.3
-  ERM-3288 Fix permission on /erm/files/{id}/raw in mod-agreements
ERM-3282

Release 11.0.3

---

src/components/TitleFilters/TitleFilters.js
src/components/TitleFilters/TitleFilters.test.js
src/components/TitleFilters/testResources.js
src/routes/TitlesRoute/TitlesRoute.js
translations/ui-agreements/en.json

* add subType filter
* name it material type

ERM-3277 Add Material Type filter (Print/Electronic) to Title search

---

src/components/views/Basket/Basket.js

fix: Fixes to accommodate stripes changes
Stripes changed to use `formatter` prop in Selection for rendering display as well as the options. This means that a `null` option is now a legitimate use case, which we had not protected for. Added in null safety here, and this also means that the display on selection is equivalent to the options render, which might not be desired but at least this works.
ERM-3362

ERM-3362: Error on viewing ERM basket

---

package.json
src/components/AgreementSections/Lines/Lines.test.js

Added an example test which uses MemoryRouter to allow for testing of "to" buttons

test: Lines routing test

---

src/components/AgreementSections/ContentTypesFieldArray/ContentTypesFieldArray.js
src/routes/AgreementEditRoute/AgreementEditRoute.js

* change agreementContentTypes initialValues on submit

ERM-3392 Changes to the field content type are not saved, but a success message is displayed

---

package.json

Removed previously required nwsapi resolution pinning version to 2.2.13, issues caused have been resolved as of 2.2.16 release

build: Removed nwsapi resolution
